# Generated by Django 4.1.6 on 2023-03-08 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_order1_delete_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_item", models.CharField(max_length=1000)),
                ("ordered_by", models.CharField(default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("order_quantity", models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name="Order1",
        ),
    ]
